name: build-deploy

on: push

jobs:
  build-deploy:
    if: github.event.head_commit.message == 'deploy'
    runs-on: ubuntu-latest
    name: build and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install  
      - name: Build
        run: CI=false npm run build --if-present
      - name: deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./build/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.DEPLOY_PATH }}
